## 使用轻量级的 Python 镜像作为基础
#FROM python:3.9-slim-buster
#
## 设置工作目录
#WORKDIR /app
#
## 将 requirements.txt 复制到容器中
#COPY requirements.txt .
#
## 安装依赖项
#RUN pip install --no-cache-dir --upgrade -r requirements.txt
#
## 将应用程序代码复制到容器中
#COPY . .
#
## 暴露 Flask 应用程序运行的端口
#EXPOSE 5000
#
## 定义启动应用程序的命令
#CMD ["flask", "run", "--host=0.0.0.0"]